terraform_sets:
  - name: dev-pbr-gims
    type: gims
    load-balancer: False
    root: /Users/s0279879/Documents/GitHub/dev/cgsdev/terraform-repo/gims
    var-files:
      - generic.tfvars
      - dev-pbr.tfvars
    state-file: tfstate-files/dev-pbr.tfstate
  - name: dev-pbr-loom
    type: loom
    load-balancer: False
    root: /Users/s0279879/Documents/GitHub/dev/cgsdev/terraform-repo/loom
    var-files:
      - generic.tfvars
      - dev-pbr.tfvars
    state-file: tfstate-files/dev-pbr.tfstate
