terraform_sets:
  - name: dev-loom
    type: loom
    load-balancer: False
    root: /Users/s0279879/Documents/GitHub/dev/cgsdev/terraform-repo/loom
    var-files:
      - generic.tfvars
      - development.tfvars
    state-file: tfstate-files/development.tfstate
  - name: dev-gims
    type: gims
    load-balancer: False
    root: /Users/s0279879/Documents/GitHub/dev/cgsdev/terraform-repo/gims
    var-files:
      - generic.tfvars
      - development.tfvars
    state-file: tfstate-files/development.tfstate
