terraform_sets:
  - name: dev-pbr-gims
    type: gims
    load-balancer: False
    root: /opt/cgsdev/terraform-repo/gims
    var-files:
      - generic.tfvars
      - dev-pbr.tfvars
      - ssh-tfvars/pbilling-ssh.tfvars
    state-file: tfstate-files/dev-pbr.tfstate
  - name: dev-pbr-loom
    type: loom
    load-balancer: False
    root: /opt/cgsdev/terraform-repo/loom
    var-files:
      - generic.tfvars
      - dev-pbr.tfvars
      - ssh-tfvars/pbilling-ssh.tfvars
    state-file: tfstate-files/dev-pbr.tfstate
  - name: dev-gims
    type: gims
    load-balancer: False
    root: /opt/cgsdev/terraform-repo/gims
    var-files:
      - generic.tfvars
      - development.tfvars
      - ssh-tfvars/pbilling-ssh.tfvars
    state-file: tfstate-files/development.tfstate
  - name: dev-loom
    type: loom
    load-balancer: False
    root: /opt/cgsdev/terraform-repo/loom
    var-files:
      - generic.tfvars
      - development.tfvars
      - ssh-tfvars/pbilling-ssh.tfvars
    state-file: tfstate-files/development.tfstate
  - name: dev-ranjan-gims
    type: gims
    load-balancer: False
    root: /opt/cgsdev/terraform-repo/gims
    var-files:
      - generic.tfvars
      - dev-ranjan.tfvars
      - ssh-tfvars/pbilling-ssh.tfvars
    state-file: tfstate-files/dev-ranjan.tfstate
  - name: dev-ranjan-loom
    type: loom
    load-balancer: False
    root: /opt/cgsdev/terraform-repo/loom
    var-files:
      - generic.tfvars
      - dev-ranjan.tfvars
      - ssh-tfvars/pbilling-ssh.tfvars
    state-file: tfstate-files/dev-ranjan.tfstate
